/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./src/components/a.vue')['default']
    B: typeof import('./src/components/b.vue')['default']
    VanButto: typeof import('vant/es')['Butto']
    VanButton: typeof import('vant/es')['Button']
  }
}
